### ISSUE TITLE
README does not match actual results and tests.

### ISSUE THREAD

**Issue by Vilsol** [CloudNativeJS/cloud-health-connect#14]
According to the README, the `Combined Health Status Code` for a `STARTING` application should be `503 UNAVAILABLE`.

However, when looking through the unit tests, I noticed that there is a test
`Health returns 200 OK and STARTING on startup check starting`.
(you can see that [here](https://github.com/CloudNativeJS/cloud-health-connect/blob/master/test/connect-cloud-health/ConnectHealth.test.ts#L326))

I would assume that this is exact opposite of the expected result?
Which one is wrong? The README or actual code?

**Comment by dpkirchner** [comment]
I believe it's a code issue. You can see here that the intention was for `STARTING` to return 503:

https://github.com/CloudNativeJS/cloud-health-connect/blob/master/src/connect-cloud-health/ConnectHealth.ts#L73

but in the combined `HealthEndpoint` code it explicitly returns `OK` for `STARTING`, just as in the `LivenessEndpoint`.

For now I'm just going to use `ReadnessEndpoint` in my express code.

**Comment by andrewhughes101** [comment]
Hi @Vilsol, thanks for spotting this

This should be fixed by #27
