### ISSUE TITLE
LivenessCheck with chained promises

### ISSUE THREAD

**Issue by tanoshii** [CloudNativeJS/cloud-health-connect#9]
Hi! I'm having a problem with the promise for LivenessCheck. I'm not sure if I'm doing something wrong with the promises. This is my case: 
My service needs to resolve two chained promises to determine its status

```javascript
const promise = doSetup()
    .then(() => checkStatus())
const livenessCheck =  new LivenessCheck('My service', promise)
```

doSetup() and checkStatus() return a Promise. If doSetup() or checkStatus() fail I want to show the status as DOWN during the LivenessCheck.

But somehow the result is always DOWN, even if both promises are resolved. I tried to declare or handle the promises in different ways, even removing the logic from my service, and the result is always the same.

```javascript
  const promise = new Promise((resolve, reject) => {
    return Promise.resolve("Always sucessful promise 1")
      .then(() => {
        return Promise.resolve("Always successful promise 2") 
      })
      .then(resolve)
      .catch(reject)
  })
const livenessCheck =  new LivenessCheck('My service', promise) // Always DOWN
```

Also, if I force the second promise to reject, the result is status DOWN but the reason is empty even though I setted a message at rejection.

What could be the problem? 
Thank you

**Comment by andrewhughes101** [comment]
Hi @tanoshii there have been a few changes to the module since you raised this issue, does the sample code below represent the behaviour you were trying to achieve. This seems to be working now, let me know if not.

```js
const express = require('express');
const app = express();
const port = 3000;

const health = require('@cloudnative/health-connect');
let healthcheck = new health.HealthChecker();

const livePromise = () => new Promise((resolve, _reject) => {
  setTimeout(() => {
    console.log('LIVE!');
    resolve();
  }, 10)
}).then(() => {
  return new Promise((resolve,reject) => {
    setTimeout(() => {
      console.log("LIVE2!");
      resolve();
    },10)
  })
});

let liveCheck = new health.LivenessCheck("liveCheck", livePromise);
healthcheck.registerLivenessCheck(liveCheck);

app.get('/', (req,res) => {
  res.send("Issue number 9");
});

app.use('/live',health.LivenessEndpoint(healthcheck));
app.use('/liveStatus', (req,res) => {
  res.send(liveCheck);
})
app.listen(port);
```

**Comment by tanoshii** [comment]
Hi @andrewhughes101, it worked as expected, thank you so much!

**Comment by andrewhughes101** [comment]
Thanks for letting me know. Im gonna go ahead and close this now.
